# -*- coding: utf-8 -*-
"""fcc_sms_text_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10wrumrd2B4UCPy54EVHoArngnKD-SS5Y

In this challenge, you need to create a machine learning model that will classify SMS messages as either "ham" or "spam". A "ham" message is a normal message sent by a friend. A "spam" message is an advertisement or a message sent by a company.

You should create a function called `predict_message` that takes a message string as an argument and returns a list. The first element in the list should be a number between zero and one that indicates the likeliness of "ham" (0) or "spam" (1). The second element in the list should be the word "ham" or "spam", depending on which is most likely.

For this challenge, you will use the [SMS Spam Collection dataset](http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/). The dataset has already been grouped into train data and test data.

The first cell import the libraries and data. The final cell tests your model and function. Add your code in between these cells.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow import keras
from keras.preprocessing import sequence

!wget https://cdn.freecodecamp.org/project-data/sms/train-data.tsv
!wget https://cdn.freecodecamp.org/project-data/sms/valid-data.tsv

def reader_data(file_name):
  data = pd.read_csv(
      file_name, 
      sep='\t', 
      header=None,
      names=['label', 'text'])
  return data

train_data = reader_data('train-data.tsv')
valid_data = reader_data('valid-data.tsv')

print(f'TRAIN DATA \n {train_data.tail()} \n\n VALID DATA \n {valid_data.tail()} \n\n TRAIN DATA SUMMARY')

print(train_data.info(), '\n\n TRAIN DATA SUM of NULL')
print(train_data.isnull().sum(), '\n\n VALID DATA SUMMARY')
print(valid_data.info(), '\n\n TEST DATA SUM of NULL')
print(valid_data.isnull().sum())

def preprocess(data):
  X = np.array(data.iloc[:,1])
  y = data.iloc[:,0].astype('category').cat.codes
  return X, y

X_train, y_train = preprocess(train_data)
X_valid, y_valid = preprocess(valid_data)
encoder = keras.layers.TextVectorization()
encoder.adapt(X_train)

model = tf.keras.Sequential([
    encoder,
    tf.keras.layers.Embedding(
        input_dim=len(encoder.get_vocabulary()),
        output_dim=64,
        mask_zero=True),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

callbacks = [
    tf.keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=3), 
    tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0.001, patience=5)
]

model.compile(optimizer='adam', metrics=['accuracy'], loss='binary_crossentropy')
model.summary()

history = model.fit(
    x = X_train,
    y = y_train, 
    epochs=50,
    validation_data = (X_valid, y_valid),
    callbacks = callbacks
)

# function to predict messages based on model
# (should return list containing prediction and label, ex. [0.008318834938108921, 'ham'])
def predict_message(pred_text):
  prediction = model.predict(np.array([pred_text])).item()
  if prediction < 0.5:
    pred_list = [f'{prediction:.2e}', 'ham']
  else:
    pred_list = [f'{prediction:.2e}', 'spam']
  return pred_list

pred_text = 'how are you doing today'

prediction = predict_message(pred_text)
print(prediction)

# Run this cell to test your function and model. Do not modify contents.
def test_predictions():
  test_messages = ["how are you doing today",
                   "sale today! to stop texts call 98912460324",
                   "i dont want to go. can we try it a different day? available sat",
                   "our new mobile video service is live. just install on your phone to start watching.",
                   "you have won £1000 cash! call to claim your prize.",
                   "i'll bring it tomorrow. don't forget the milk.",
                   "wow, is your arm alright. that happened to me one time too"
                  ]

  test_answers = ["ham", "spam", "ham", "spam", "spam", "ham", "ham"]
  passed = True

  for msg, ans in zip(test_messages, test_answers):
    prediction = predict_message(msg)
    if prediction[1] != ans:
      passed = False

  if passed:
    print("You passed the challenge. Great job!")
  else:
    print("You haven't passed yet. Keep trying.")

test_predictions()